[dev]
  command = "pnpm dev"
  targetPort = 5174
  port = 8888

[build]
  command = "pnpm build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/_api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200